#!/usr/bin/env ruby

require_relative '../application'

require "slop"

def import_bsym_exchanges
  importer = BsymExchangesImporter.new
  importer.import
end

def import_bsym
  importer = BsymSecuritiesImporter.new
  importer.import
end

def import_csi
  importer = CsiDataImporter.new
  importer.import
end

def main
  opts = Slop.parse do |o|
    o.bool '-b', '--bsym', 'Import Bloomberg Open Symbology - Exchanges and Symbols'
    o.bool '-c', '--csi', 'Import CSI Data - Exchanges and Symbols'
    o.bool '-e', '--exchanges', 'Import Bloomberg Open Symbology Exchanges'
    o.string '--config', 'Config file path'
    o.on '--help' do
      puts o
      exit
    end
  end

  import_functions = []

  import_functions << :import_bsym_exchanges if opts.bsym? || opts.exchanges?
  import_functions << :import_bsym if opts.bsym?
  import_functions << :import_csi if opts.csi?

  if import_functions
    Application.load(opts[:config] || Application::DEFAULT_CONFIG_FILE_PATH)

    import_functions.each {|fn_name| send(fn_name) }
  end
end

main if __FILE__ == $0

# #!/bin/bash
#
# ruby importers/import_securities.rb
# ruby importers/import_eod_bars.rb
# ruby importers/import_dividends_and_splits.rb
