#!/usr/bin/env ruby

require_relative '../application'

def seed
  CorporateActionType.create(name: "Cash Dividend")
  CorporateActionType.create(name: "Split")

  FundamentalDimension.create(name: "INST", description: "Instantaneous point in time snapshot.")
  FundamentalDimension.create(name: "ARY", description: "As reported, annually.")
  FundamentalDimension.create(name: "ARQ", description: "As reported, quarterly.")
  FundamentalDimension.create(name: "ART-Q", description: "As reported, trailing twelve months (TTM). Aggregated over quarterly observations.")
  FundamentalDimension.create(name: "MRY", description: "Most-recent reported, annually.")
  FundamentalDimension.create(name: "MRQ", description: "Most-recent reported, quarterly.")
  FundamentalDimension.create(name: "MRT-Q", description: "Most-recent reported, trailing twelve months (TTM). Aggregated over quarterly observations.")

  DataVendor.create(name: "Quandl")

  UpdateFrequency.create(label: "Daily")
  UpdateFrequency.create(label: "Weekly")
  UpdateFrequency.create(label: "Monthly")
  UpdateFrequency.create(label: "Quarterly")
  UpdateFrequency.create(label: "Yearly")
  UpdateFrequency.create(label: "Irregular")
end

def main
  Application.load(ARGV.first || Application::DEFAULT_CONFIG_FILE_PATH)
  puts "Seeding database."
  seed
end

main if __FILE__ == $0
