#!/usr/bin/env ruby

require_relative '../application'

def seed
  CorporateActionType.create(name: "Cash Dividend")
  CorporateActionType.create(name: "Split")

  FundamentalDimension.create(name: "INST", description: "Instantaneous point in time snapshot.")
  FundamentalDimension.create(name: "ARY", description: "As reported, annually.")
  FundamentalDimension.create(name: "ARQ", description: "As reported, quarterly.")
  FundamentalDimension.create(name: "ART", description: "As reported, trailing twelve months (TTM).")
  FundamentalDimension.create(name: "MRY", description: "Most-recent reported, annually.")
  FundamentalDimension.create(name: "MRQ", description: "Most-recent reported, quarterly.")
  FundamentalDimension.create(name: "MRT", description: "Most-recent reported, trailing twelve months (TTM).")

  DataVendor.create(name: "Quandl")
end

def main
  Application.load(ARGV.first || Application::DEFAULT_CONFIG_FILE_PATH)
  seed
end

main if __FILE__ == $0
