#!/usr/bin/env ruby

require_relative '../application'

def seed
  CorporateActionType.create(name: "Cash Dividend")
  CorporateActionType.create(name: "Split")
end

def main
  Application.load(ARGV.first || Application::DEFAULT_CONFIG_FILE_PATH)
  seed
end

main if __FILE__ == $0
